export type FallbackAuditLocation = {
  file: string;
  line: number;
  term: "DIRECT_FALLBACK" | "fallback" | "crowFly" | "candidateToAttachment" | "directLine";
  snippet: string;
  routeGeometryRisk: boolean;
};

export const fallbackAuditReport: { search: string; fallbackLocations: FallbackAuditLocation[] } = {
  search: 'rg "DIRECT_FALLBACK|fallback|crowFly|candidateToAttachment|directLine" hyperlinx-dal-dev/src hyperlinx-dal-dev/server -n',
  fallbackLocations: [
    { file: "src/api/dalStorage.ts", line: 169, term: "fallback", snippet: "Storage quota fallback object; not route geometry.", routeGeometryRisk: false },
    { file: "src/api/dalStorage.ts", line: 170, term: "fallback", snippet: "Returns storage warning fallback when browser storage estimates are unavailable.", routeGeometryRisk: false },
    { file: "src/api/dalStorage.ts", line: 175, term: "fallback", snippet: "Returns storage warning fallback when quota bytes are unavailable.", routeGeometryRisk: false },
    { file: "src/api/dalStorage.ts", line: 192, term: "fallback", snippet: "Returns storage warning fallback after storage estimate failure.", routeGeometryRisk: false },
    { file: "src/api/dalClient.ts", line: 604, term: "fallback", snippet: "Local fallback Twin state; not route geometry.", routeGeometryRisk: false },
    { file: "src/api/inventoryRecovery.ts", line: 90, term: "fallback", snippet: "Count parsing fallback for inventory recovery metadata.", routeGeometryRisk: false },
    { file: "src/api/inventoryRecovery.ts", line: 95, term: "fallback", snippet: "Text parsing fallback for inventory recovery metadata.", routeGeometryRisk: false },
    { file: "src/api/reasoningRegistry.ts", line: 100, term: "fallback", snippet: "Reasoning capability fallback; not route geometry.", routeGeometryRisk: false },
    { file: "src/affinity/attachmentStrategyEngine.ts", line: 78, term: "fallback", snippet: "fallbackCost is a cost estimate only; no route geometry.", routeGeometryRisk: false },
    { file: "src/affinity/attachmentStrategyEngine.ts", line: 85, term: "fallback", snippet: "Uses fallbackCost for estimated construction cost only.", routeGeometryRisk: false },
    { file: "src/commercial/quoteEngine.ts", line: 6, term: "fallback", snippet: "Numeric parsing fallback for quote calculations.", routeGeometryRisk: false },
    { file: "src/components/ConstraintEvidenceStrip.tsx", line: 61, term: "fallback", snippet: "Displays constraint-analysis fallback mode.", routeGeometryRisk: false },
    { file: "src/components/ConstraintEvidenceStrip.tsx", line: 97, term: "fallback", snippet: "Displays constraint fallback reasons.", routeGeometryRisk: false },
    { file: "src/components/ReasoningHealthDashboard.tsx", line: 115, term: "fallback", snippet: "Dashboard copy for reasoning fallback services.", routeGeometryRisk: false },
    { file: "src/config/dalApi.ts", line: 13, term: "fallback", snippet: "DAL API target configuration fallback.", routeGeometryRisk: false },
    { file: "src/config/dalApi.ts", line: 18, term: "fallback", snippet: "Returns configured DAL API fallback target.", routeGeometryRisk: false },
    { file: "src/geocoding/geocodeEngine.ts", line: 51, term: "fallback", snippet: "Geocoding supports deterministic fallback option.", routeGeometryRisk: false },
    { file: "src/geocoding/geocodeEngine.ts", line: 393, term: "fallback", snippet: "Geocoding may fall back to deterministic coordinates when no real geocoder is configured.", routeGeometryRisk: false },
    { file: "src/geocoding/geocodeEngine.ts", line: 396, term: "fallback", snippet: "Runs deterministic geocoder only when fallback is enabled.", routeGeometryRisk: false },
    { file: "src/gis/geo.ts", line: 73, term: "fallback", snippet: "Map center fallback coordinate; not route geometry.", routeGeometryRisk: false },
    { file: "src/gis/geo.ts", line: 75, term: "fallback", snippet: "Returns fallback map center when bounds are unavailable.", routeGeometryRisk: false },
    { file: "src/mapkernel/MapLayerManager.ts", line: 166, term: "DIRECT_FALLBACK", snippet: "Map Kernel has a ROUTE_AUTHORITY_DIRECT_FALLBACK layer for visible diagnostics.", routeGeometryRisk: true },
    { file: "src/mapkernel/MapLayerManager.ts", line: 198, term: "fallback", snippet: "Render identity token fallback.", routeGeometryRisk: false },
    { file: "src/prism/prismOpportunityEngine.ts", line: 164, term: "fallback", snippet: "Candidate CSV type normalization fallback.", routeGeometryRisk: false },
    { file: "src/prism/prismOpportunityEngine.ts", line: 170, term: "fallback", snippet: "Candidate CSV default candidate type fallback.", routeGeometryRisk: false },
    { file: "src/routing/CertifiedRouteAuthority.ts", line: 5, term: "DIRECT_FALLBACK", snippet: "CertifiedRoute type includes DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/routing/CertifiedRouteAuthority.ts", line: 13, term: "DIRECT_FALLBACK", snippet: "CertifiedRoute state includes DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/routing/CertifiedRouteAuthority.ts", line: 75, term: "crowFly", snippet: "CertifiedRoute stores crowFlyFeet for route authority diagnostics.", routeGeometryRisk: true },
    { file: "src/routing/AttachmentAwareRouteEngine.ts", line: 14, term: "DIRECT_FALLBACK", snippet: "Route engineering alternatives still support DIRECT_FALLBACK in diagnostics.", routeGeometryRisk: true },
    { file: "src/routing/AttachmentAwareRouteEngine.ts", line: 58, term: "DIRECT_FALLBACK", snippet: "Marks direct or attachment-direct route modes as direct fallback.", routeGeometryRisk: true },
    { file: "src/routing/AttachmentAwareRouteEngine.ts", line: 153, term: "DIRECT_FALLBACK", snippet: "Propagates routed DIRECT_FALLBACK mode into an attachment-aware alternative.", routeGeometryRisk: true },
    { file: "src/routing/AttachmentAwareRouteEngine.ts", line: 160, term: "fallback", snippet: "Route engineering diagnostic note for direct fallback.", routeGeometryRisk: true },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 81, term: "fallback", snippet: "Constraint provenance fallback flags; not route creation.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 295, term: "fallback", snippet: "Reference layer source-label fallback.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 341, term: "fallback", snippet: "Builds constraint fallback reasons when reference layers are missing.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 353, term: "fallback", snippet: "Marks constraint analysis fallback mode when route/reference geometry is invalid.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 696, term: "fallback", snippet: "Water analysis switches to unknown/fallback when provenance is incomplete.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 702, term: "fallback", snippet: "Water audit labels fallback analysis method.", routeGeometryRisk: false },
    { file: "src/routing/ConstraintAnalysisEngine.ts", line: 728, term: "fallback", snippet: "Constraint certification is blocked when fallback mode is active.", routeGeometryRisk: false },
    { file: "src/routing/DeterministicStreetDrivewayRouting.ts", line: 6, term: "DIRECT_FALLBACK", snippet: "Legacy deterministic helper can emit DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/routing/DeterministicStreetDrivewayRouting.ts", line: 19, term: "DIRECT_FALLBACK", snippet: "Legacy deterministic helper can label attachment method as DIRECT_FALLBACK_ATTACHMENT.", routeGeometryRisk: true },
    { file: "src/routing/DeterministicStreetDrivewayRouting.ts", line: 183, term: "DIRECT_FALLBACK", snippet: "Legacy deterministic helper returns empty/fallback state for invalid coordinates.", routeGeometryRisk: true },
    { file: "src/routing/DeterministicStreetDrivewayRouting.ts", line: 217, term: "DIRECT_FALLBACK", snippet: "Legacy deterministic helper selects DIRECT_FALLBACK for two-point routes.", routeGeometryRisk: true },
    { file: "src/routing/DeterministicStreetDrivewayRouting.ts", line: 224, term: "DIRECT_FALLBACK", snippet: "Legacy deterministic helper labels direct fallback attachment.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 133, term: "DIRECT_FALLBACK", snippet: "Classifies geometry length <= 2 as DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 139, term: "DIRECT_FALLBACK", snippet: "Preserves DIRECT_FALLBACK route authority state.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 154, term: "DIRECT_FALLBACK", snippet: "Blocks direct fallback routes from authoritative certification.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 179, term: "crowFly", snippet: "Computes crowFlyFeet between candidate and attachment for route authority diagnostics.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 227, term: "crowFly", snippet: "Initializes crowFlyFeet for route authority records.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 274, term: "DIRECT_FALLBACK", snippet: "Can promote edited geometry out of DIRECT_FALLBACK when more than two vertices exist.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityEngine.ts", line: 286, term: "DIRECT_FALLBACK", snippet: "Throws when DIRECT_FALLBACK geometry is certified.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityRenderer.ts", line: 6, term: "DIRECT_FALLBACK", snippet: "Maps DIRECT_FALLBACK state to routeAuthorityDirectFallback layer.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityRenderer.ts", line: 13, term: "DIRECT_FALLBACK", snippet: "Labels DIRECT_FALLBACK render layer.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityRenderer.ts", line: 22, term: "DIRECT_FALLBACK", snippet: "Styles DIRECT_FALLBACK route geometry as blocked/advisory.", routeGeometryRisk: true },
    { file: "src/routing/RouteAuthorityRenderer.ts", line: 34, term: "DIRECT_FALLBACK", snippet: "Displays DIRECT FALLBACK label.", routeGeometryRisk: true },
    { file: "src/routing/StreetGraphRouter.ts", line: 30, term: "fallback", snippet: "StreetGraphRouter audit always reports fallbackUsed false.", routeGeometryRisk: false },
    { file: "src/routing/StreetGraphRouter.ts", line: 263, term: "fallback", snippet: "StreetGraphRouter console audit emits fallbackUsed.", routeGeometryRisk: false },
    { file: "src/routing/StreetGraphRouter.ts", line: 292, term: "fallback", snippet: "StreetGraphRouter failure audit reports fallbackUsed false.", routeGeometryRisk: false },
    { file: "src/routing/StreetGraphRouter.ts", line: 402, term: "fallback", snippet: "StreetGraphRouter success audit reports fallbackUsed false.", routeGeometryRisk: false },
    { file: "src/serviceability/streetPathEngine.ts", line: 85, term: "fallback", snippet: "Legacy street path adapter maps DIRECT_FALLBACK to FALLBACK_DIRECT_SEGMENT.", routeGeometryRisk: true },
    { file: "src/serviceability/streetPathEngine.ts", line: 105, term: "DIRECT_FALLBACK", snippet: "Legacy street path adapter rewrites DIRECT_FALLBACK_ATTACHMENT display method.", routeGeometryRisk: true },
    { file: "src/street/SnapAuthorityEngine.ts", line: 94, term: "fallback", snippet: "Snap authority chooses first available candidate if no stronger snap candidate exists.", routeGeometryRisk: true },
    { file: "src/street/SnapAuthorityEngine.ts", line: 102, term: "fallback", snippet: "Snap authority emits selected fallback snap authority fields.", routeGeometryRisk: true },
    { file: "src/spatial/roadEngine.ts", line: 27, term: "fallback", snippet: "Spatial road model estimates fallback road distance.", routeGeometryRisk: false },
    { file: "src/spatial/roadEngine.ts", line: 53, term: "fallback", snippet: "Spatial road engine uses fallback road distance estimate.", routeGeometryRisk: false },
    { file: "src/scopeversion/scopeVersionUtils.ts", line: 39, term: "fallback", snippet: "Numeric parsing fallback for ScopeVersion values.", routeGeometryRisk: false },
    { file: "src/types/dal.ts", line: 321, term: "DIRECT_FALLBACK", snippet: "DAL route authority type includes DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/types/dal.ts", line: 328, term: "DIRECT_FALLBACK", snippet: "DAL route mode type includes DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/workspaces/DALInventoryWorkspace.tsx", line: 86, term: "fallback", snippet: "Status text for deleting local fallback inventory graph.", routeGeometryRisk: false },
    { file: "src/workspaces/DALInventoryWorkspace.tsx", line: 104, term: "fallback", snippet: "Inventory workspace copy describes fallback records.", routeGeometryRisk: false },
    { file: "src/workspaces/InventoryRecoveryWorkspace.tsx", line: 306, term: "fallback", snippet: "Inventory Recovery describes IndexedDB as cache/fallback.", routeGeometryRisk: false },
    { file: "src/workspaces/OperationalIntelligenceWorkspace.tsx", line: 167, term: "DIRECT_FALLBACK", snippet: "Operational Intelligence counts direct fallback certified routes.", routeGeometryRisk: true },
    { file: "src/workspaces/PrismSiteDecisionWorkspace.tsx", line: 152, term: "fallback", snippet: "Constraint count display fallback string.", routeGeometryRisk: false },
    { file: "src/workspaces/PrismSiteDecisionWorkspace.tsx", line: 259, term: "fallback", snippet: "Routing Audit displays fallbackUsed.", routeGeometryRisk: false },
    { file: "src/workspaces/RouteEngineeringWorkspace.tsx", line: 200, term: "DIRECT_FALLBACK", snippet: "Route Engineering workspace can classify two-point geometry as DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/workspaces/RouteEngineeringWorkspace.tsx", line: 307, term: "fallback", snippet: "Route Engineering copy warns direct fallback blocks downstream work.", routeGeometryRisk: true },
    { file: "src/workspaces/RouteEngineeringWorkspace.tsx", line: 430, term: "fallback", snippet: "Route Engineering counts direct fallback routes.", routeGeometryRisk: true },
    { file: "src/workspaces/RouteEngineeringWorkspace.tsx", line: 445, term: "DIRECT_FALLBACK", snippet: "Route Engineering filter exposes DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "src/workspaces/RouteEngineeringWorkspace.tsx", line: 471, term: "crowFly", snippet: "Route Engineering displays crow-fly feet.", routeGeometryRisk: true },
    { file: "src/workspaces/TranslateWorkspace.tsx", line: 235, term: "fallback", snippet: "KML placemark name fallback.", routeGeometryRisk: false },
    { file: "src/workspaces/TranslateWorkspace.tsx", line: 303, term: "fallback", snippet: "Route name fallback for parsed source geometry.", routeGeometryRisk: false },
    { file: "src/workspaces/TranslateWorkspace.tsx", line: 325, term: "fallback", snippet: "Parser fallback label for source geometry issues.", routeGeometryRisk: false },
    { file: "server/routes/certified-routes.js", line: 32, term: "DIRECT_FALLBACK", snippet: "Server certified-route contract preserves DIRECT_FALLBACK state.", routeGeometryRisk: true },
    { file: "server/routes/certified-routes.js", line: 57, term: "DIRECT_FALLBACK", snippet: "Server route normalization can classify <=2-point geometry as DIRECT_FALLBACK.", routeGeometryRisk: true },
    { file: "server/routes/certified-routes.js", line: 75, term: "crowFly", snippet: "Server certified-route response includes crowFlyFeet.", routeGeometryRisk: true },
    { file: "server/routes/certified-routes.js", line: 137, term: "DIRECT_FALLBACK", snippet: "Server rejects certification of DIRECT_FALLBACK routes.", routeGeometryRisk: true },
  ],
};
