import {
  PD003_PRODUCTION_DOCTRINE_ID,
  PD003_PRODUCTION_DOCTRINE_VERSION,
  PRODUCTION_PROFILE_LIBRARY_AUTHORITY,
  type ProductionProfile,
  type ProductionProfileId,
  type ProductionProfileLibrary,
} from "./PD003ProductionContracts";

function profile(input: Omit<ProductionProfile, "noScopeVersionCreation">): ProductionProfile {
  return { ...input, noScopeVersionCreation: true };
}

export const DEFAULT_PRODUCTION_PROFILES: ProductionProfile[] = [
  profile({ profileId: "PLOW_STANDARD", displayName: "Standard Plow", description: "Standard plow production from audit assumptions.", applicableObjectClasses: ["LINEAR_CONSTRUCTION"], applicableObjectTypes: ["PLOW_SEGMENT", "CONDUIT"], productionUnit: "feet", productionRate: 5280, productionRateUnit: "ft/day", crewType: "PLOW_CREW", crewCountDefault: 1, crewSizeDefault: 3, equipmentRequired: ["Plow"], laborRate: 5, laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 92, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "OSP Production", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Plow production: 5280 ft/day", "Plow labor: 5 USD/ft"] }),
  profile({ profileId: "BORE_DIRT_STANDARD", displayName: "Directional Bore Dirt", description: "Standard dirt HDD production from audit assumptions.", applicableObjectClasses: ["LINEAR_CONSTRUCTION", "CONSTRAINT"], applicableObjectTypes: ["DIRECTIONAL_BORE_SEGMENT", "ROAD_CROSSING", "RIVER_CROSSING", "WATER_CROSSING", "DOT_CROSSING"], productionUnit: "feet", productionRate: 600, productionRateUnit: "ft/day", crewType: "HDD_CREW", crewCountDefault: 1, crewSizeDefault: 4, equipmentRequired: ["HDD Rig", "Mud system"], laborRate: 11, laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 88, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Directional Bore", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Directional bore dirt production: 600 ft/day", "Directional bore dirt labor: 11 USD/ft"] }),
  profile({ profileId: "BORE_ROCK_STANDARD", displayName: "Directional Bore Rock", description: "Rock HDD production with configurable labor rate.", applicableObjectClasses: ["LINEAR_CONSTRUCTION", "CONSTRAINT"], applicableObjectTypes: ["ROCK_BORE_SEGMENT", "ROCK_REVIEW"], productionUnit: "feet", productionRate: 300, productionRateUnit: "ft/day", crewType: "HDD_CREW", crewCountDefault: 1, crewSizeDefault: 4, equipmentRequired: ["Rock-capable HDD Rig"], laborRate: "CONFIGURABLE", laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost requires approved labor override", confidence: 60, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Directional Bore Rock", humanOverrideAllowed: true, requiresHumanReview: true, notes: ["Directional bore rock production: 300 ft/day", "Labor rate configurable and review required"] }),
  profile({ profileId: "OPEN_TRENCH_DIRT_STANDARD", displayName: "Open Trench Dirt", description: "Standard open trench dirt production.", applicableObjectClasses: ["LINEAR_CONSTRUCTION"], applicableObjectTypes: ["OPEN_TRENCH_SEGMENT"], productionUnit: "feet", productionRate: 300, productionRateUnit: "ft/day", crewType: "TRENCH_CREW", crewCountDefault: 1, crewSizeDefault: 4, equipmentRequired: ["Excavator", "Trench safety"], laborRate: 38, laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 84, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Open Trench", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Open trench dirt production: 300 ft/day", "Open trench labor: 38 USD/ft"] }),
  profile({ profileId: "OPEN_TRENCH_ROCK_STANDARD", displayName: "Open Trench Rock", description: "Rock trench production requiring human review.", applicableObjectClasses: ["LINEAR_CONSTRUCTION"], applicableObjectTypes: ["OPEN_TRENCH_SEGMENT", "ROCK_REVIEW"], productionUnit: "feet", productionRate: 150, productionRateUnit: "ft/day", crewType: "TRENCH_CREW", crewCountDefault: 1, crewSizeDefault: 4, equipmentRequired: ["Rock saw", "Excavator"], laborRate: "CONFIGURABLE", laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost requires approved labor override", confidence: 58, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Open Trench Rock", humanOverrideAllowed: true, requiresHumanReview: true, notes: ["Open trench rock production: 150 ft/day"] }),
  profile({ profileId: "FIBER_BLOW_STANDARD", displayName: "Fiber Blow", description: "Standard fiber blowing production.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["FIBER"], productionUnit: "feet", productionRate: 5280, productionRateUnit: "ft/day", crewType: "FIBER_CREW", crewCountDefault: 1, crewSizeDefault: 2, equipmentRequired: ["Fiber blower"], laborRate: 1, laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 90, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Fiber Placement", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Fiber blowing production: 5280 ft/day", "Fiber placement labor: 1 USD/ft"] }),
  profile({ profileId: "FIBER_PULL_STANDARD", displayName: "Fiber Pull", description: "Standard fiber pulling production.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["FIBER"], productionUnit: "feet", productionRate: 5280, productionRateUnit: "ft/day", crewType: "FIBER_CREW", crewCountDefault: 1, crewSizeDefault: 2, equipmentRequired: ["Fiber pulling setup"], laborRate: 1, laborRateUnit: "USD/ft", materialRate: "INCLUDED", materialRateUnit: "USD/ft", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 90, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Fiber Placement", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Fiber pulling production: 5280 ft/day"] }),
  profile({ profileId: "SPLICE_864_STANDARD", displayName: "864 Count Splice", description: "Splice production for 864-count closures.", applicableObjectClasses: ["CONTAINED_CONNECTION"], applicableObjectTypes: ["SPLICE_CASE"], productionUnit: "termination", productionRate: 1728, productionRateUnit: "terminations/day", crewType: "SPLICE_CREW", crewCountDefault: 1, crewSizeDefault: 2, equipmentRequired: ["Splice trailer", "Fusion splicer"], laborRate: 15, laborRateUnit: "USD/termination", materialRate: "INCLUDED", materialRateUnit: "USD/termination", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate", confidence: 86, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Splicing", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["One 864-count closure per day per crew", "Butt splice production: 1728 terminations/day"] }),
  profile({ profileId: "TESTING_INCLUDED_WITH_SPLICING", displayName: "Testing Included With Splicing", description: "Testing included with splicing unless overridden.", applicableObjectClasses: ["CONTAINED_CONNECTION", "LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["SPLICE_CASE", "FIBER"], productionUnit: "included", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "SPLICE_CREW", crewCountDefault: 1, crewSizeDefault: 2, equipmentRequired: ["OTDR"], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: "INCLUDED", materialRateUnit: "included", scheduleParticipation: true, costParticipation: false, paymentParticipation: true, defaultDurationFormula: "included with splicing schedule", defaultCostFormula: "no additive cost unless overridden", confidence: 82, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Testing", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Testing included with splicing unless overridden"] }),
  profile({ profileId: "RESTORATION_INCLUDED_STANDARD", displayName: "Restoration Included", description: "Restoration included with drilling/plowing schedule allowance unless overridden.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["RESTORATION"], productionUnit: "included", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "OSP_CREW", crewCountDefault: 1, crewSizeDefault: 3, equipmentRequired: ["Restoration tools"], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: "INCLUDED", materialRateUnit: "included", scheduleParticipation: true, costParticipation: false, paymentParticipation: true, defaultDurationFormula: "included with drilling/plowing schedule allowance", defaultCostFormula: "no additive cost unless overridden", confidence: 80, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Restoration", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Restoration included unless overridden"] }),
  profile({ profileId: "HYDROVAC_INCLUDED_STANDARD", displayName: "Hydrovac Included", description: "Hydrovac included in OSP construction unless overridden.", applicableObjectClasses: ["LINEAR_CONSTRUCTION"], applicableObjectTypes: ["PLOW_SEGMENT", "DIRECTIONAL_BORE_SEGMENT", "OPEN_TRENCH_SEGMENT"], productionUnit: "included", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "OSP_CREW", crewCountDefault: 1, crewSizeDefault: 3, equipmentRequired: ["Hydrovac"], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: "INCLUDED", materialRateUnit: "included", scheduleParticipation: true, costParticipation: false, paymentParticipation: true, defaultDurationFormula: "included in OSP construction", defaultCostFormula: "no additive cost unless overridden", confidence: 78, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "OSP Construction", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Hydrovac included in OSP construction unless overridden"] }),
  profile({ profileId: "PROJECT_MANAGEMENT_STANDARD", displayName: "Project Management", description: "Project management loaded cost based on production duration.", applicableObjectClasses: ["AUTHORITY"], applicableObjectTypes: ["COMMERCIAL_APPROVAL", "ENGINEERING_REVIEW", "PERMIT_PACKAGE"], productionUnit: "day", productionRate: "INCLUDED", productionRateUnit: "duration-based", crewType: "PROJECT_MANAGEMENT", crewCountDefault: 1, crewSizeDefault: 1, equipmentRequired: [], laborRate: "INCLUDED", laborRateUnit: "duration-based", materialRate: "INCLUDED", materialRateUnit: "included", annualLoadedCost: 100000, scheduleParticipation: true, costParticipation: true, paymentParticipation: false, defaultDurationFormula: "schedule based on production duration", defaultCostFormula: "projectManagementCost = productionDurationDays / 260 * annualLoadedCost", confidence: 84, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Project Management", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Project manager loaded cost: 100000 USD/year"] }),
  profile({ profileId: "MATERIAL_CONDUIT_1_5_STANDARD", displayName: "1.5 Inch Conduit Material", description: "Standard conduit material cost.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["CONDUIT"], productionUnit: "feet", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "MATERIAL", crewCountDefault: 1, crewSizeDefault: 1, equipmentRequired: [], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: 0.65, materialRateUnit: "USD/ft", scheduleParticipation: false, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "material only", defaultCostFormula: "materialCost = quantity * materialRate", confidence: 90, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Materials", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Conduit material: 0.65 USD/ft"] }),
  profile({ profileId: "MATERIAL_FUTUREPATH_STANDARD", displayName: "FuturePath Material", description: "Standard FuturePath material cost.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["FUTUREPATH", "INNERDUCT"], productionUnit: "feet", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "MATERIAL", crewCountDefault: 1, crewSizeDefault: 1, equipmentRequired: [], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: 1.8, materialRateUnit: "USD/ft", scheduleParticipation: false, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "material only", defaultCostFormula: "materialCost = quantity * materialRate", confidence: 88, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Materials", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["FuturePath material: 1.8 USD/ft"] }),
  profile({ profileId: "MATERIAL_FIBER_864_STANDARD", displayName: "864 Fiber Material", description: "Standard 864-count fiber material cost.", applicableObjectClasses: ["LINEAR_INFRASTRUCTURE"], applicableObjectTypes: ["FIBER"], productionUnit: "feet", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "MATERIAL", crewCountDefault: 1, crewSizeDefault: 1, equipmentRequired: [], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: 5, materialRateUnit: "USD/ft", scheduleParticipation: false, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "material only", defaultCostFormula: "materialCost = quantity * materialRate", confidence: 90, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Materials", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["864-count fiber: 5 USD/ft"] }),
  profile({ profileId: "MATERIAL_HANDHOLE_STANDARD", displayName: "Handhole Material and Labor", description: "Standard handhole labor and material cost.", applicableObjectClasses: ["PRIMARY_STRUCTURE"], applicableObjectTypes: ["HANDHOLE", "MANHOLE", "VAULT"], productionUnit: "each", productionRate: 1, productionRateUnit: "ea/day", crewType: "CIVIL_CREW", crewCountDefault: 1, crewSizeDefault: 3, equipmentRequired: ["Mini excavator"], laborRate: 315, laborRateUnit: "USD/ea", materialRate: 900, materialRateUnit: "USD/ea", scheduleParticipation: true, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "durationDays = quantity / productionRate", defaultCostFormula: "productionCost = quantity * laborRate; materialCost = quantity * materialRate", confidence: 86, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Structures", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Handhole labor: 315 USD/ea", "Handhole material: 900 USD/ea"] }),
  profile({ profileId: "MATERIAL_SPLICE_CASE_STANDARD", displayName: "Splice Case Material", description: "Standard splice case material cost.", applicableObjectClasses: ["CONTAINED_CONNECTION"], applicableObjectTypes: ["SPLICE_CASE"], productionUnit: "each", productionRate: "INCLUDED", productionRateUnit: "included", crewType: "MATERIAL", crewCountDefault: 1, crewSizeDefault: 1, equipmentRequired: [], laborRate: "INCLUDED", laborRateUnit: "included", materialRate: 850, materialRateUnit: "USD/ea", scheduleParticipation: false, costParticipation: true, paymentParticipation: true, defaultDurationFormula: "material only", defaultCostFormula: "materialCost = quantity * materialRate", confidence: 88, authorityMode: "AUDIT_AUTHORITY", sourceWorkbook: "Commercial Estimate Audit", sourceSheet: "Materials", humanOverrideAllowed: true, requiresHumanReview: false, notes: ["Splice case material: 850 USD/ea"] }),
];

export function createProductionProfileLibrary(generatedAt = "2026-07-03T00:00:00.000Z"): ProductionProfileLibrary {
  return {
    libraryId: "PD003-PRODUCTION-PROFILE-LIBRARY",
    doctrineId: PD003_PRODUCTION_DOCTRINE_ID,
    doctrineVersion: PD003_PRODUCTION_DOCTRINE_VERSION,
    authority: PRODUCTION_PROFILE_LIBRARY_AUTHORITY,
    profiles: DEFAULT_PRODUCTION_PROFILES,
    byProfileId: Object.fromEntries(DEFAULT_PRODUCTION_PROFILES.map((item) => [item.profileId, item])) as Record<ProductionProfileId, ProductionProfile>,
    generatedAt,
    noScopeVersionCreation: true,
  };
}
