import type { DesignDoctrine } from "./DesignDoctrine";

export const DESIGN_DOCTRINES: Record<DesignDoctrine["networkClass"], DesignDoctrine> = {
  LONG_HAUL: {
    designDoctrineId: "DD-LONG-HAUL-V1",
    networkClass: "LONG_HAUL",
    defaultTopology: "LINEAR",
    allowedTopologies: ["LINEAR"],
    defaultProtection: "NONE",
    optionalProtections: ["PATH_PROTECTED"],
    rules: [
      "Connect major markets.",
      "Optimize for latency.",
      "Minimize unnecessary turns.",
      "Laterals attach to the backbone.",
      "No rings.",
      "No mesh.",
      "No metro assumptions.",
    ],
    constructionDoctrine: {
      constructionProfileId: "LONG_HAUL_BURIED_BACKBONE",
      preferredConstructionType: "BURIED",
      constructionAssumptions: ["Long continuous backbone construction.", "ROW and crossing review expected before engineering."],
      infrastructureAssumptions: ["Backbone-oriented facilities.", "Laterals are subordinate attachments."],
      futureRoutingConstraints: ["Preserve long-haul continuity.", "Avoid unnecessary deviations unless human engineering approves."],
    },
    facilitySpacingDoctrine: {
      facilityProfileId: "LONG_HAUL_SPACING_V1",
      regenSpacingMiles: 60,
      vaultSpacingFeet: 2500,
      lateralAssumption: "BACKBONE_ATTACH",
      notes: ["Regen and vault spacing are fixture defaults only.", "No stationing is generated in this phase."],
    },
    materialDoctrine: {
      materialProfileId: "LONG_HAUL_MATERIAL_V1",
      defaultProducts: ["DUCT_PLUS_FIBER", "BACKBONE_FIBER"],
      preferredBackboneFiberCount: 432,
      preferredDuctConfiguration: "Multi-duct backbone with reserve capacity.",
      overrideAllowed: true,
      notes: ["Users may override material defaults in later phases."],
    },
    readOnly: true,
    noRouting: true,
    noGeometryCreation: true,
  },
  MIDDLE_MILE: {
    designDoctrineId: "DD-MIDDLE-MILE-V1",
    networkClass: "MIDDLE_MILE",
    defaultTopology: "LINEAR",
    allowedTopologies: ["LINEAR"],
    defaultProtection: "PATH_PROTECTED",
    optionalProtections: ["PATH_PROTECTED"],
    rules: ["Aggregate communities.", "Connect POPs.", "Connect access networks.", "Support laterals.", "No rings.", "No mesh."],
    constructionDoctrine: {
      constructionProfileId: "MIDDLE_MILE_BURIED_AGGREGATION",
      preferredConstructionType: "BURIED",
      constructionAssumptions: ["Community aggregation route.", "County and municipal interfaces expected."],
      infrastructureAssumptions: ["POP and access handoff support.", "Laterals remain subordinate."],
      futureRoutingConstraints: ["Preserve community aggregation behavior.", "Avoid metro ring assumptions."],
    },
    facilitySpacingDoctrine: {
      facilityProfileId: "MIDDLE_MILE_SPACING_V1",
      regenSpacingMiles: 45,
      vaultSpacingFeet: 1800,
      lateralAssumption: "BACKBONE_ATTACH",
      notes: ["Spacing is doctrine-only and fixture-derived."],
    },
    materialDoctrine: {
      materialProfileId: "MIDDLE_MILE_MATERIAL_V1",
      defaultProducts: ["DUCT_PLUS_FIBER", "BACKBONE_FIBER", "LATERAL"],
      preferredBackboneFiberCount: 288,
      preferredDuctConfiguration: "Backbone duct with access lateral allowances.",
      overrideAllowed: true,
      notes: ["No takeoff is calculated in this phase."],
    },
    readOnly: true,
    noRouting: true,
    noGeometryCreation: true,
  },
  METRO: {
    designDoctrineId: "DD-METRO-V1",
    networkClass: "METRO",
    defaultTopology: "LINEAR",
    allowedTopologies: ["LINEAR", "RING"],
    defaultProtection: "RING_PROTECTED",
    optionalProtections: ["NONE", "RING_PROTECTED"],
    rules: [
      "Serve buildings, enterprise sites, carrier hotels, and data centers.",
      "Support multiple entrances.",
      "Assume dense infrastructure.",
      "Routes generally remain inside one metropolitan area.",
    ],
    constructionDoctrine: {
      constructionProfileId: "METRO_DENSE_UNDERGROUND",
      preferredConstructionType: "UNDERGROUND_DUCT",
      constructionAssumptions: ["Dense urban construction.", "Traffic control and building entrance review expected."],
      infrastructureAssumptions: ["Vault and cabinet density is higher than backbone routes.", "Building entrances may be required."],
      futureRoutingConstraints: ["Remain inside the metro unless reclassified as middle-mile.", "Prefer access-friendly corridors."],
    },
    facilitySpacingDoctrine: {
      facilityProfileId: "METRO_FACILITY_DENSITY_V1",
      vaultSpacingFeet: 900,
      cabinetDensity: "HIGH",
      buildingEntranceAssumption: "MULTIPLE",
      lateralAssumption: "ACCESS_DISTRIBUTION",
      notes: ["Metro density is doctrine-only until engineering validation."],
    },
    materialDoctrine: {
      materialProfileId: "METRO_MATERIAL_V1",
      defaultProducts: ["DARK_FIBER", "MICRODUCT", "LATERAL"],
      preferredBackboneFiberCount: 144,
      preferredDuctConfiguration: "Urban duct and lateral distribution.",
      overrideAllowed: true,
      notes: ["Material profile is advisory and deterministic."],
    },
    readOnly: true,
    noRouting: true,
    noGeometryCreation: true,
  },
  CAMPUS: {
    designDoctrineId: "DD-CAMPUS-V1",
    networkClass: "CAMPUS",
    defaultTopology: "MESH",
    allowedTopologies: ["MESH", "RING"],
    defaultProtection: "MESH_PROTECTED",
    optionalProtections: ["RING_PROTECTED", "MESH_PROTECTED"],
    rules: [
      "Support hyperscaler campuses, GPU clusters, and enterprise campuses.",
      "Assume extremely short spans.",
      "Support multiple duct systems.",
      "Support multiple entrances.",
      "Support multiple redundant paths.",
    ],
    constructionDoctrine: {
      constructionProfileId: "CAMPUS_REDUNDANT_DUCT",
      preferredConstructionType: "UNDERGROUND_DUCT",
      constructionAssumptions: ["Short-span redundant duct systems.", "Campus standards dominate route assumptions."],
      infrastructureAssumptions: ["Multiple entrances and redundant paths are expected.", "Cabinet and vault placement is campus-specific."],
      futureRoutingConstraints: ["Optimize for redundancy and access over distance.", "Do not apply long-haul assumptions."],
    },
    facilitySpacingDoctrine: {
      facilityProfileId: "CAMPUS_FACILITY_DENSITY_V1",
      vaultSpacingFeet: 500,
      cabinetDensity: "HIGH",
      buildingEntranceAssumption: "MULTIPLE",
      lateralAssumption: "CAMPUS_DISTRIBUTION",
      notes: ["Campus density is fixture-only in Phase 7.0A."],
    },
    materialDoctrine: {
      materialProfileId: "CAMPUS_MATERIAL_V1",
      defaultProducts: ["DUCT_PLUS_FIBER", "MICRODUCT", "LATERAL"],
      preferredBackboneFiberCount: 864,
      preferredDuctConfiguration: "Redundant campus duct banks with reserve pathways.",
      overrideAllowed: true,
      notes: ["No campus routing is generated in this phase."],
    },
    readOnly: true,
    noRouting: true,
    noGeometryCreation: true,
  },
};

export const designDoctrineFixtures = Object.freeze(Object.values(DESIGN_DOCTRINES));
