import { deriveRouteCertificationState } from "../certification/CertificationAuthority";
import { hashRouteGeometry, type ConstraintEvidencePackage } from "../routing/ConstraintAnalysisEngine";
import type { DALCoordinate } from "../types/dal";

type ConstraintEvidenceStripProps = {
  title?: string;
  evidence?: ConstraintEvidencePackage | null;
  currentGeometry?: DALCoordinate[];
  expectedHash?: string;
};

function fmt(value: number | undefined) {
  return Number(value || 0).toLocaleString();
}

function countLabel(evidence: ConstraintEvidencePackage | null | undefined, key: keyof ConstraintEvidencePackage["summary"]) {
  if (!evidence) return "UNKNOWN";
  if (evidence.unknownCounts?.[key]) return "UNKNOWN";
  return fmt(evidence.summary[key]);
}

export default function ConstraintEvidenceStrip({ title = "Constraint Evidence", evidence, currentGeometry, expectedHash }: ConstraintEvidenceStripProps) {
  const currentHash = currentGeometry?.length ? hashRouteGeometry(currentGeometry) : expectedHash;
  const expected = expectedHash ?? currentHash;
  const stale = Boolean(evidence && currentHash && evidence.routeGeometryHash !== currentHash);
  const drift = Boolean(evidence && expected && evidence.routeGeometryHash !== expected);
  const summary = evidence?.summary;
  const registry = evidence?.constraintRegistrySnapshot;
  const referenceOnlyLayers = registry?.layers.filter((layer) => layer.certificationUse === "REFERENCE_ONLY") ?? [];
  const usableLayers = registry?.layers.filter((layer) => layer.certificationUse === "USABLE_FOR_CERTIFICATION" && layer.status === "LOADED") ?? [];
  const authority = currentHash
    ? deriveRouteCertificationState({
        routeGeometryHash: currentHash,
        constraintEvidencePackage: evidence,
      })
    : null;

  return (
    <div className="dal-status">
      <b>{title}</b>
      <div className="dal-metrics">
        <span>Evidence ID: {evidence?.evidenceId ?? "missing"}</span>
        <span>Route Geometry Hash: {evidence?.routeGeometryHash ?? currentHash ?? "n/a"}</span>
        <span>Generated At: {evidence?.generatedAt ?? "n/a"}</span>
        <span>Generated By: {evidence?.generatedBy ?? "ConstraintAnalysisEngine"}</span>
        <span>Water Crossings: {countLabel(evidence, "waterCrossings")}</span>
        <span>Road Crossings: {countLabel(evidence, "roadCrossings")}</span>
        <span>Rail Crossings: {countLabel(evidence, "railroadCrossings")}</span>
        <span>Constructability: {fmt(evidence?.constructabilityScore)}</span>
        <span>Certification Readiness: {evidence?.certificationReadiness ?? "n/a"}</span>
        <span>Water Layer Loaded: {evidence?.waterCrossingAudit.waterLayerLoaded ? "TRUE" : "FALSE"}</span>
        <span>Water Feature Count: {fmt(evidence?.waterCrossingAudit.waterFeatureCount)}</span>
        <span>Water Intersections Found: {fmt(evidence?.waterCrossingAudit.waterIntersectionsFound)}</span>
        <span>Water Analysis: {evidence?.waterCrossingAudit.analysisMethod ?? "UNKNOWN"}</span>
        <span>Constraint Completeness: {registry ? `${registry.completeness.completenessPercent}%` : "UNKNOWN"}</span>
        <span>Missing Layers: {registry?.completeness.missingLayers.join(", ") || "none recorded"}</span>
        <span>Reference-Only Layers: {referenceOnlyLayers.map((layer) => layer.layerType).join(", ") || "none"}</span>
        <span>Usable Layers: {usableLayers.map((layer) => layer.layerType).join(", ") || "none"}</span>
        <span>Evidence Grade: {authority?.evidenceGrade ?? "UNKNOWN_CONSTRAINT_EVIDENCE"}</span>
        <span>Route Certification State: {authority?.state ?? "DRAFT_ROUTE"}</span>
        <span>Fallback Mode: {evidence?.provenance.fallbackMode ? "TRUE" : "FALSE"}</span>
        <span>Evidence Status: {stale ? "STALE CONSTRAINT EVIDENCE" : drift ? "CONSTRAINT DRIFT DETECTED" : evidence ? "CURRENT" : "MISSING"}</span>
      </div>
      {evidence?.diagnostics.constraintLayerDiagnostics?.length ? (
        <div className="dal-table-wrap">
          <table className="dal-table">
            <thead>
              <tr>
                <th>Layer</th>
                <th>Loaded</th>
                <th>Features</th>
                <th>Authority</th>
                <th>Certification Use</th>
                <th>Intersections</th>
                <th>Coverage</th>
              </tr>
            </thead>
            <tbody>
              {evidence.diagnostics.constraintLayerDiagnostics.map((layer) => (
                <tr key={layer.constraintClass}>
                  <td>{layer.constraintClass}</td>
                  <td>{layer.layerLoaded ? "YES" : "NO"}</td>
                  <td>{fmt(layer.featureCount)}</td>
                  <td>{layer.authority}</td>
                  <td>{layer.certificationUse}</td>
                  <td>{fmt(layer.intersectionCount)}</td>
                  <td>{layer.coverage?.bbox ? layer.coverage.bbox.map((value) => Number(value).toFixed(5)).join(", ") : "n/a"}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : null}
      {evidence?.waterCrossingAudit.intersectionCoordinates.length ? (
        <pre className="dal-pre">{JSON.stringify({ waterIntersectionCoordinates: evidence.waterCrossingAudit.intersectionCoordinates }, null, 2)}</pre>
      ) : null}
      {evidence?.provenance.fallbackReasons.length ? <div className="dal-status">{evidence.provenance.fallbackReasons.join(" ")}</div> : null}
    </div>
  );
}
